export const CLASS_NAMES = {
  "0": "airan-katyk",
  "1": "almond",
  "2": "apple",
  "3": "artichoke",
  "4": "arugula",
  "5": "asparagus",
  "6": "avocado",
  "7": "bacon",
  "8": "banana",
  "9": "beans",
  "10": "beet",
  "11": "bell pepper",
  "12": "black olives",
  "13": "blackberry",
  "14": "blueberry",
  "15": "boiled chicken",
  "16": "bread",
  "17": "broccoli",
  "18": "buckwheat",
  "19": "cabbage",
  "20": "cakes",
  "21": "carrot",
  "22": "cashew",
  "23": "casserole with meat and vegetables",
  "24": "cauliflower",
  "25": "celery",
  "26": "cereal based cooked food",
  "27": "cheese",
  "28": "chickpeas",
  "29": "chips",
  "30": "cooked eggplant",
  "31": "cooked food based on meat",
  "32": "cooked food meat with vegetables",
  "33": "cooked zucchini",
  "34": "cookies",
  "35": "corn",
  "36": "crepe",
  "37": "cucumber",
  "38": "cutlet",
  "39": "desserts",
  "40": "egg product",
  "41": "eggplant",
  "42": "fish",
  "43": "fried chicken",
  "44": "fried eggs",
  "45": "fried fish",
  "46": "fried meat",
  "47": "fruits",
  "48": "granola",
  "49": "grapes",
  "50": "green beans",
  "51": "herbs",
  "52": "hummus",
  "53": "ice-cream",
  "54": "irimshik",
  "55": "juice",
  "56": "kiwi",
  "57": "lavash",
  "58": "legumes",
  "59": "lemon",
  "60": "mandarin",
  "61": "mango",
  "62": "mashed potato",
  "63": "meat product",
  "64": "melon",
  "65": "mixed berries",
  "66": "mixed nuts",
  "67": "mushrooms",
  "68": "onion",
  "69": "orange",
  "70": "pasta",
  "71": "pastry",
  "72": "peanut",
  "73": "pear",
  "74": "peas",
  "75": "pecan",
  "76": "pickled cabbage",
  "77": "pickled squash",
  "78": "pie",
  "79": "pineapple",
  "80": "pizza",
  "81": "plov",
  "82": "porridge",
  "83": "potatoes",
  "84": "pumpkin",
  "85": "radish",
  "86": "raspberry",
  "87": "rice",
  "88": "salad fresh",
  "89": "salad leaves",
  "90": "salad with fried meat veggie",
  "91": "salad with sauce",
  "92": "sandwich",
  "93": "sausages",
  "94": "seafood",
  "95": "smetana",
  "96": "snacks",
  "97": "snacks bread",
  "98": "souces",
  "99": "soup-plain",
  "100": "soy product",
  "101": "spinach",
  "102": "strawberry",
  "103": "suzbe",
  "104": "sweet potatoes",
  "105": "tomato",
  "106": "tomato souce",
  "107": "tushpara-wo-soup",
  "108": "vegetable based cooked food",
  "109": "waffles",
  "110": "walnut",
  "111": "watermelon",
  "112": "zucchini"
};
export const NUM_CLASSES = 113;
